
<!--Common footer -->				
			<div class="bottom">
			
					<p>CSC 174 Advance Front End Development, Project One</p>
						
					<p>One Man Army Team members: Jack Zhang, Isaac Mosebrook, Tara Anacker, Stephanie Pollocks</p>
						
					<p>For more information about the team, please see the <a class="c-link" href="colophon.php">Colophon</a></p>
			</div>

	<script src="js/menu-highlighter.js"></script>
        <script src="js/plugins.js"></script>
        <script src="js/main.js"></script>

